function [methodinfo,structs,enuminfo,ThunkLibName]=tescommex
%TESCOMMEX Create structures to define interfaces found in 'TESCOM'.

%This function was generated by loadlibrary.m parser version 1.1.6.32 on Sun Jan 22 00:26:52 2012
%perl options:'TESCOM.i -outfile=tescommex.m'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival);
ThunkLibName=[];
% short _stdcall Startup ( void ); 
fcns.name{fcnNum}='Startup'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='int16'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
% short _stdcall Shutdown ( void ); 
fcns.name{fcnNum}='Shutdown'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='int16'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
% unsigned short _stdcall ReadNetVar ( unsigned short , unsigned short , unsigned short *); 
fcns.name{fcnNum}='ReadNetVar'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='uint16'; fcns.RHS{fcnNum}={'uint16', 'uint16', 'uint16Ptr'};fcnNum=fcnNum+1;
% unsigned short _stdcall WriteNetVar ( unsigned short , unsigned short , unsigned short ); 
fcns.name{fcnNum}='WriteNetVar'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='uint16'; fcns.RHS{fcnNum}={'uint16', 'uint16', 'uint16'};fcnNum=fcnNum+1;
structs.segment_struct.members=struct('type', 'int8', 'variable1', 'uint16', 'variable2', 'uint16');
methodinfo=fcns;