function [methodinfo,structs,enuminfo,ThunkLibName]=mx_inpout32
%MX_INPOUT32 Create structures to define interfaces found in 'inpout32h'.

%This function was generated by loadlibrary.m parser version 1.1.6.29 on Tue Jul 13 16:17:02 2010
%perl options:'inpout32h.i -outfile=mx_inpout32.m'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival);
ThunkLibName=[];
% short _stdcall Inp32 ( short PortAddress ); 
fcns.name{fcnNum}='Inp32'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='int16'; fcns.RHS{fcnNum}={'int16'};fcnNum=fcnNum+1;
% void _stdcall Out32 ( short PortAddress , short data ); 
fcns.name{fcnNum}='Out32'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}={'int16', 'int16'};fcnNum=fcnNum+1;
methodinfo=fcns;